@hostname = http://localhost:3500

@exampleLocation = 625aecd851ff4f0be43465fa
@exampleLocationPost = "625aecd851ff4f0be43465fa"
@userId1 = "625be2a1be49dfb27b9d1583"
@userId2 = "625be292be49dfb27b9d157e"
@userId3 = "625be2babe49dfb27b9d1588"
@playingTeam = "625c351caaa5395203d8b5f9"
@playingTeamGet = 625c351caaa5395203d8b5f9

@lat = 35
@long = 34

### POST Area
post {{hostname}}/api/area
Content-Type: application/json

{
    "coordinates": [{{lat}},{{long}}]
    , "country": "Israel"
    , "area": "Nof Hagalil"
}

### POST Area
post {{hostname}}/api/area
Content-Type: application/json

{
    "coordinates": [34.7915, 31.2530]
    , "country": "Israel"
    , "area": "Be'er Sheva"
}

### Get Areas
get {{hostname}}/api/area

{

}

### POST Question
post {{hostname}}/api/question/english
Content-Type: application/json

{
    "location" = {{exampleLocationPost}}
    , "question": "When Tel Aviv Established"
    , "answers": ["Answer1", "Answer2", "Answer3", "Answer4"  ]
    , "rightAnswer": 3
}


### GET Questions
get {{hostname}}/api/question/english?lat={{lat}}&long={{long}}
Content-Type: application/json

{

}


### POST User
post {{hostname}}/api/user
Content-Type: application/json

{
    "name" : "Tamar" 
    , "age" : "42"
    , "email" : "tamar@gmail.com"
    , "password" : "123"
}


### GET Users
get {{hostname}}/api/user

{

}



### PUT User (language, location)
put {{hostname}}/api/user
Content-Type: application/json

{
    "user": {{userId1}}
    ,"language" : "english" 
    , "coordinates" : [{{lat}},{{long}}]
}

### PATCH User (name, age, email, password)
# # #



### POST PlayingTeam
post {{hostname}}/api/playingTeam
Content-Type: application/json

{
    "organizer": {{userId1}}
}

### PUT player to PlayingTeam
patch {{hostname}}/api/playingTeam/player
Content-Type: application/json

{
    "playingTeam": {{playingTeam}}
    , "player" : {{userId2}}
}


### PATCH player to PlayingTeam
patch {{hostname}}/api/playingTeam/player
Content-Type: application/json

{
    "playingTeam": {{playingTeam}}
    , "player" : {{userId3}}
}

### PATCH player to PlayingTeam
patch {{hostname}}/api/playingTeam/accept
Content-Type: application/json

{
    "playingTeam": {{playingTeam}}
    , "player" : {{userId2}}
}


### GET PlayingTeam, global info function
get {{hostname}}/api/playingTeam/{{playingTeamGet}}

{

}



### PATCH player to PlayingTeam
patch {{hostname}}/api/playingTeam/answer
Content-Type: application/json

{
    "playingTeam": {{playingTeam}}
    , "player" : {{userId3}}
    , "question": "625af52e2e8d035041eadd8"
    , "answer": 2
}



### GET Users
get {{hostname}}/api/user/find?user=625be2a1be49dfb27b9d1583

{

}





